#https://github.com/blacklabelops/jira/blob/master/docker-compose.yml

version: '3'

services:
  jira:
    restart: always
    depends_on:
      - postgresql
    image: blacklabelops/jira
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
      - 'JIRA_DB_PASSWORD=password'
      - 'SETENV_JVM_MINIMUM_MEMORY=384m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=1g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"



  confluence:
    restart: always
    depends_on:
      - postgresql
    image: blacklabelops/confluence
    networks:
      - jiranet
    volumes:
      - confluencedata:/var/atlassian/confluence
    ports:
      - '80:8090'
      - '8091:8091'
    environment:
#      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
#      - 'JIRA_DB_PASSWORD=password'
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'CONFLUENCE_PROXY_NAME='
      - 'CONFLUENCE_PROXY_PORT='
      - 'CONFLUENCE_PROXY_SCHEME='
      - 'CONFLUENCE_DELAYED_START='
      - 'DOCKER_WAIT_HOST=postgresql'
      - 'DOCKER_WAIT_PORT=5432'
    labels:
      com.blacklabelops.description: "Atlassian Confluence"
      com.blacklabelops.service: "confluence"

  bitbucket:
    restart: always
    image: blacklabelops/bitbucket
    depends_on:
      - postgresql
    networks:
      - bitbucketnet
    volumes:
      - bitbucketdata:/var/atlassian/bitbucket
    ports:
      - '80:7990'
    environment:
      - 'BITBUCKET_PROXY_NAME='
      - 'BITBUCKET_PROXY_PORT='
      - 'BITBUCKET_PROXY_SCHEME='
      - 'BITBUCKET_DELAYED_START='
      - 'DOCKER_WAIT_HOST=postgresql'
      - 'DOCKER_WAIT_PORT=5432'
    labels:
      com.blacklabelops.description: "Atlassian Bitbucket"
      com.blacklabelops.service: "bitbucket"


  postgresql:
    image: blacklabelops/postgres
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

volumes:
  jiradata:
    external: false
  bitbucketdata:
    external: false
  bitbucketdata:
    external: false  
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge